# Base image
FROM node:latest

# Create app directory
WORKDIR /app

# Install dependencies first by copying only the package.json and package-lock.json
# This ensures that npm install is re-run only when package files change
COPY app/package*.json ./

# Install app dependencies
RUN npm install

# Copy the entire app source code after installing dependencies
COPY app/backend.js /app/

# Install node server daemon
RUN npm install pm2 -g

# Expose port 3000
EXPOSE 4000

# Start Nginx
CMD ["pm2-runtime", "start", "backend.js"]
